# Same Alpine version as dind (https://hub.docker.com/_/docker)
FROM rust:1-alpine3.22 AS builder

RUN apk add --no-cache pkgconfig musl-dev curl

# Required for shell processes backend
RUN curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | sh -s -- --to /usr/local/bin

WORKDIR /build
COPY . .

RUN cargo install --path bbox-processes-server

# Required for shell processes backend
RUN cargo install shell-compose

# -- Runtime stage
FROM docker:dind-rootless

USER root

COPY --from=builder /usr/local/cargo/bin/bbox-processes-server /usr/local/bin/
COPY --from=builder /usr/local/cargo/bin/shell-compose* /usr/local/bin/
COPY --from=builder /usr/local/bin/just /usr/local/bin/

# Inject application start into entrypoint
RUN sed --in-place '/exec rootlesskit/i bbox-processes-server serve &' /usr/local/bin/dockerd-entrypoint.sh

USER rootless

ENV BBOX_WEBSERVER__SERVER_ADDR="0.0.0.0:8080"
EXPOSE 8080
